name: run random.sh

on:
  schedule:
    - cron: "0 0 * * *" # At 00:00 everyday

jobs:
  random:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.random_result.outputs.result1 }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - id: random_result
        name: run random.sh
        run: echo "result1=$(./random.sh)" >> $GITHUB_OUTPUT
        shell: bash
  send:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{needs.random.outputs.output1}}
