name: run print_random.sh

on:
  schedule:
    - cron: "0 0 * * *" # At 00:00 everyday

jobs:
  random:
    runs-on: ubuntu-latest
    outputs:
      tech_note: ${{ steps.random_tech_note.outputs.note }}
      non_tech_note: ${{ steps.random_non_tech_note.outputs.note }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - id: random_tech_note
        name: run print_random.sh tech
        run: | 
            result=$(./print_random.sh)
            if [[ $result != "DO_NOTHING" ]]; then
              echo $result
              echo "note=$result" >> $GITHUB_OUTPUT
            fi
        shell: bash
      - id: random_non_tech_note
        name: run print_random.sh non_tech
        run: | 
            result=$(./print_random.sh non_tech)
            if [[ $result != "DO_NOTHING" ]]; then
              echo $result
              echo "note=$result" >> $GITHUB_OUTPUT
            fi
        shell: bash
  send:
    runs-on: ubuntu-latest
    needs: random
    steps:
      - name: send telegram message for tech note
        if: needs.random.outputs.tech_note != ''
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ needs.random.outputs.tech_note }}
      - name: send telegram message for non_tech note
        if: needs.random.outputs.non_tech_note != ''
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ needs.random.outputs.non_tech_note }}
